name: Deploy Hugo site to GitHub Pages

# whenever you push to main (or trigger manually)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read       # for checkout
  pages: write         # to deploy
  id-token: write      # for actions/deploy-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Build
        run: hugo --minify
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

